### ISSUE TITLE
Compiling to LuaJIT bytecode

### ISSUE THREAD

**Issue by rochus-keller** [hengestone/lua-languages#11]
I'm particularly interested in reusing LuaJIT on bytecode level. As far as I can see my Oberon implementation currently seems to be the only one directly compiling to LuaJIT bytecode, i.e. everyone else seems to transpile to Lua source code (maybe there is another language doing this which I missed up to now). The major disadvantage of Lua as an intermediate language is the fact that line numbers reported by the debugger refer to the wrong source file (the intermediate Lua instead of the original source). I implemented a full IDE (https://github.com/rochus-keller/oberon/#oberon-ide-features) which - with a slight modification of LuaJIT - even supports row and column numbers (not only row numbers as with the original Lua engines). I don't see a way how to do this when Lua is the intermediate language. Also worth mentioning that the Oberon code compiled to bytecode runs nearly the same speed as the Oberon to native compiled version and twice as fast as the Oberon to Lua source code transpiled version (see https://github.com/rochus-keller/Oberon/blob/master/testcases/Hennessy_Results).

For me (and maybe others too) it would be helpful to explicitly track on the list which languages compile to Lua source code or LuaJIT bytecode. For people who would like to implement a bytecode backend you could add https://github.com/rochus-keller/LjTools and https://github.com/franko/luajit-lang-toolkit. Thanks.

**Comment by hengestone** [comment]
Definitely, I'll add your tools soon :)
Very impressive work btw!

**Comment by rochus-keller** [comment]
Thanks, appreciate.
