### ISSUE TITLE
Alternative JS-based syntax for Lua

### ISSUE THREAD

**Issue by saharNooby** [hengestone/lua-languages#16]
This is neither a completely new language, nor a JS to Lua compiler. Just an alternative syntax with syntaxic sugar that is missing in Lua.
https://github.com/saharNooby/lua-js-syntax

Also, other similar projects (not mine) you may be interested in:
- [ljs](https://github.com/mingodad/ljs): C Lua VM fork with JS-like syntax.
- [jual](https://github.com/sajonoso/jual): C Lua VM fork with JS-like syntax that is a ECMAScript subset.
- [Killa](https://github.com/ex/Killa): C Lua VM fork with JS-like syntax.

**Comment by hengestone** [comment]
I finally added your project as well as ljs. Seems like jual and Killa are not maintained, so leaving them out for now.
Thanks!
