### ISSUE TITLE
could someone build a windows x64 exe?

### ISSUE THREAD

**Issue by vkensou** [hengestone/lua-languages#27]
I am interest in functional language. but i don't know how to build listed project.

I only build Hypatia success. all other falled.

Functional
https://amulet.works/ An ML-like functional programming language that transpiles to lua
https://github.com/kindl/Hypatia Hypatia, an ML-like language that transpiles to Lua
https://github.com/ptol/oczor Haskell-like language that compiles to Lua, Javascript, Emacs lisp and Ruby
https://github.com/iitalics/Lua-ML Basic ML language
https://github.com/hengestone/pumpkin ML-like language with an experimental Lua back-end
https://github.com/minoki/LunarML A Standard ML compiler that produces Lua

**Comment by hengestone** [comment]
Not really relevant here: ask the various project authors.
