### ISSUE TITLE
Oberon to LuaJIT transpiler

### ISSUE THREAD

**Issue by rochus-keller** [hengestone/lua-languages#3]
Nice collection, just discovered now. In case you're interested, this code currently translates Oberon-07 to LuaJIT specific Lua source code: https://github.com/rochus-keller/Oberon/. Here is an article describing the concepts: https://medium.com/@rochus.keller/implementing-call-by-reference-and-call-by-name-in-lua-47b9d1003cc2. A direct to bytecode compiler is on its way. The goal is to have an easy to handle platform to implement various frontends of statically/strongly typed languages, leaner than an LLVM solution, and easier and faster than the RPython toolchain.
There is already some infrastructure for LuaJIT bytecode analysis and an alternative interpreter implementation for exploration purpose: https://github.com/rochus-keller/LjTools.

**Comment by hengestone** [comment]
Wow, thanks for the info, I'll add it to the list!
I've never looked much into Oberon, got sidetracked by the C-mafia after using Pascal in the 90s :)
