### ISSUE TITLE
Archived/unmaintained Languages

### ISSUE THREAD

**Issue by mystery-z** [hengestone/lua-languages#33]
I've just noticed that Amulet is no longer being maintained and the owner of the Github repo has archived it. Is it okay for Amulet to stay on, or should there be a different section/category called archived languages?

**Comment by Andre-LA** [comment]
Making a new "unmaintained" or "archived" category it's also a good option.

**Comment by mystery-z** [comment]
> Making a new "unmaintained" or "archived" category it's also a good option.

I'll put in a PR and put `[unmaintained]` before all the languages that aren't being actively worked on, this seems like a cleaner option.
