### ISSUE TITLE
Found these typescript to lua projects

### ISSUE THREAD

**Issue by r-lyeh** [hengestone/lua-languages#6]
- https://github.com/TypeScriptToLua/TypeScriptToLua
- https://github.com/roblox-ts/roblox-ts
- https://github.com/ASDAlexander77/TypeScriptLua

PS: Nice project!

**Comment by xavier83** [comment]
Also there is https://github.com/mun-lang/mun , not a typescript translator though.

**Comment by hengestone** [comment]
@r-lyeh Thanks, I added those. Maybe hopefully but unlikely, having this list helps these projects find each other...  :)

@xavier83 Interesting language, thanks for the pointer! It seems to focus on moving away from Lua though, with native and wasm targets. (?)
